MODEL:
  WEIGHTS: "bua-d2-frcn-x152.pth"
  META_ARCHITECTURE: "GeneralizedRCNN"
  ATTRIBUTE_ON: True
  BUA:
    ATTRIBUTE_ON: True
    EXTRACTOR:
      MODE: 1
      MIN_BOXES: 10
      MAX_BOXES: 20
      CONF_THRESH: 0.4
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 152
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
    SMOOTH_L1_BETA: 0.1111
    BOUNDARY_THRESH: 0
  ROI_HEADS:
    NAME: "AttributeRes5ROIHeads"
    NUM_CLASSES: 1600
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
    SMOOTH_L1_BETA: 1.
DATASETS:
  TRAIN: ("visual_genome_train", "visual_genome_val")
  TEST: ("visual_genome_test",)
SOLVER:
  # IMS_PER_BATCH: 16
  # BASE_LR: 0.02
  # STEPS: (60000, 80000)
  # MAX_ITER: 90000
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: (120000, 160000)
  MAX_ITER: 180000
INPUT:
  MIN_SIZE_TRAIN: (600,)
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
VERSION: 2