_BASE_: "base-d2.yaml"
MODEL:
  WEIGHTS: "R-101.pkl"  # the backbone weight is download from d2 at https://dl.fbaipublicfiles.com/detectron2/ImageNetPretrained/MSRA/R-101.pkl
  BUA:
    ATTRIBUTE_ON: True
    EXTRACTOR:
      MODE: 1
      MIN_BOXES: 10
      MAX_BOXES: 20
      CONF_THRESH: 0.4
  RESNETS:
    DEPTH: 101