OUTPUT_DIR: "./output_caffe152"
MODEL:
  WEIGHTS: "bua-caffe-frcn-r152.pth"
  META_ARCHITECTURE: "GeneralizedBUARCNN"
  PIXEL_MEAN: [0, 0, 0]
  ANCHOR_GENERATOR:
    SIZES: [[4, 8, 16, 32]]
  PROPOSAL_GENERATOR:
    NAME: "BUARPN"
    MIN_SIZE: 16
  BUA:
    ATTRIBUTE_ON: True
    EXTRACT_FEATS: False  # auto True when extract feats
    RESNET_VERSION: 2
    RPN:
      CONV_OUT_CHANNELS: 512
    EXTRACTOR:
      MIN_BOXES: 100
      MAX_BOXES: 100
    ATTRIBUTE:
      NUM_CLASSES: 401
  RESNETS:
    DEPTH: 152
    OUT_FEATURES: ["res4"]
    NORM: "BN"
    RES5_DILATION: 1
    STRIDE_IN_1X1: False
  BACKBONE:
    NAME: "build_bua_resnet_backbone"
    FREEZE_AT: 3
  RPN:
    HEAD_NAME: "StandardBUARPNHead"
    PRE_NMS_TOPK_TRAIN: 12000
    POST_NMS_TOPK_TRAIN: 2000
    POST_NMS_TOPK_TEST: 300
    PRE_NMS_TOPK_TEST: 6000
    BATCH_SIZE_PER_IMAGE: 64
  ROI_HEADS:
    NAME: "BUACaffeRes5ROIHeads"
    BATCH_SIZE_PER_IMAGE: 64
    SCORE_THRESH_TEST: -1.0
    NMS_THRESH_TEST: 0.3
    POSITIVE_FRACTION: 0.5
    NUM_CLASSES: 1601
  ROI_BOX_HEAD:
    POOLER_TYPE: "ROIPool"
    BBOX_REG_WEIGHTS: (1.0, 1.0, 1.0, 1.0)
DATASETS:
  TRAIN: ("visual_genome_train",)
  TEST: ("visual_genome_val",)
TEST:
  DETECTIONS_PER_IMAGE: 400
DATALOADER:
  NUM_WORKERS: 1
INPUT:
  MIN_SIZE_TRAIN: (600, )
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000

